-- Add address columns to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255),
ADD COLUMN IF NOT EXISTS city VARCHAR(255),
ADD COLUMN IF NOT EXISTS county VARCHAR(255),
ADD COLUMN IF NOT EXISTS eircode VARCHAR(255),
ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN DEFAULT FALSE; 